### ISSUE TITLE
SSL Issues?

### ISSUE THREAD

**Issue by jkporter** [starsoccer/energysmartbridge#6]
I just got an EnergySmart bridge and attempted to utilize this addon. Unfortunately, it's not working for me and no connections seem to make it to the MQTT bridge. I can confirm that DNS is working as expected and the EnergySmart bridge is sending its requests to Home Assistant.

Doing some testing locally on Windows with NGINX 1.24 I get the following using the same settings in the provided nginx.conf.

```
2024/12/10 17:24:46 [info] 37008#42412: *43 client 192.168.1.65:4098 connected to 0.0.0.0:443
2024/12/10 17:24:46 [info] 37008#42412: *43 peer closed connection in SSL handshake while SSL handshaking, client: 192.168.1.65, server: 0.0.0.0:443.
```

Attempting to use Kestrel directly (started a rewrite on top asp.net core) produces this error each time a request is made:

```
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HN8PHBJD0E7B" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HN8PHBJD0E7B" started.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
      Connection id "0HN8PHBJD0E7B" received FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
         at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
         at System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync(Boolean isAsync, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[2]
      Connection id "0HN8PHBJD0E7B" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HN8PHBJD0E7B" sending FIN because: "The Socket transport's send loop completed gracefully."
```

After inspecting wireshark connection seems to fail after Server Hello with both NGINX and Kestrel

Essentially wondering if there any thoughts as to why it appears SSL handshake isn't completing. Thanks.

**Comment by starsoccer** [comment]
Sorry for the delay, can you elaborate on what issue you had using this addon?

Regarding SSL, it took me a long time but something seems to have changed between nginx versions with SSL as I was having the same issue until I pinned the nginx version. Bumping it immediately breaks things.

**Comment by jkporter** [comment]
Thanks for the reply.

Basically, the energy smart meter attempts to connect to the home assistant addon but doesn't appear to succeed past trying to setup the SSL session and then connection is dropped. In an effort to investigate why I setup my own NGNIX server with version that was supposed to still work and a certificate that was generated matching the command in the Docker file:

`RUN openssl req  -nodes -new -x509 -sha1 -subj '/CN=energysmartwaterheater.com' -keyout /etc/nginx/energysmartwaterheater.com.key -out /etc/nginx/energysmartwaterheater.com.crt -days 3650`

I also wrote my own application (in .Net/C#) to test further.

Both appear to report similar SSL connection failures which I assume is also happing with the addon.

**Comment by starsoccer** [comment]
Hmm interesting that does seem to suggest there is some sort of issue. My gut still says its a certificate issue though but I honestly dont have much more insight into what to do besides trying different nginx versions and hoping one eventually works. I wasted quite a few days on this myself initially but the version pinned should work for everyone.

Just to confirm you dont have any reverse proxy or anything between the devices right?

**Comment by K4IZ** [comment]
Similar issues for me. Documented a bit here: https://github.com/excaliburpartners/EnergySmartBridge/issues/9#issue-2964763891

Basically, it looks like the module is trying to use NONE as the SSL cipher?

**Comment by K4IZ** [comment]
> Similar issues for me. Documented a bit here: [excaliburpartners#9 (comment)](https://github.com/excaliburpartners/EnergySmartBridge/issues/9#issue-2964763891)
> 
> Basically, it looks like the module is trying to use NONE as the SSL cipher?

A packet capture (duh) clearly shows the ciphers that the EnergySmart module can use:

Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
Cipher Suite: TLS_RSA_WITH_RC4_128_MD5 (0x0004)

**Comment by starsoccer** [comment]
The SSL protocols and ciphers are all hard coded here, https://github.com/starsoccer/energysmartbridge/blob/master/energysmartbridge/nginx.conf#L24. Just curious but are you building the containers manually or using the existing ones?

When I had ssl issues it was generally due to using a bad/incompatible nginx version. For some reason versions newer then 1.24.0 seem to not work with the device for unclear reasons

**Comment by jkporter** [comment]
My adventures of getting ASP.Net core to work (directly) have continued to fail but in a bright spot I setup this addon again today and it started to working ... partially. The addon is now accepting SSL connections, completing the HTTP request and sending the MQTT messages. Not sure what changed from when I originally opened this in last Dec. Now just to sort out why everything is unavailable but glancing at the mqtt messages they seem to all be correct and accounted for.

<img width="569" alt="Image" src="https://github.com/user-attachments/assets/4d97326c-8278-47eb-b137-d7f81edd7959" />

**Comment by starsoccer** [comment]
Im not sure if this helps or hurts but Ive refactored the project as a whole to use nodejs instead of ASP.net which may be worth a try first

**Comment by Artem-B** [comment]
I think I see the same issue. IRIS sensor attempts to connect, nginx does send the certificate back, and IRIS promptly closes the connection, without reporting any errors. It apparently does not like something about nginx's side of TLS negotiation.

I can connect and send json using curl, and it does get through to the bridge, so the issue is indeed somewhere between nginx and the IRIS sensor. What's weird, is that the sensor did manage to work for a few hours before it stopped. 

Power-cycling the sensor makes *some* SSL messages go through. I see this JSON in the logs:
```
{"level":30,"time":1744936717168,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Server listening on 8001"}
{"level":20,"time":1744937359652,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Got Request","body":{"DeviceText":"XXXXXXXX","Password":"XXXXXXXX","ModuleApi":"1.5","ModFwVer":"3.1","MasterFwVer":"02.06","MasterModelId":"B2.00","DisplayFwVer":"00.00","WifiFwVer":"C2.4.0.3.AO7","UpdateRate":"300","Mode":"Electric","SetPoint":"132","Units":"F","LeakDetect":"NotDetected","MaxSetPoint":"132","Grid":"Enabled","AvailableModes":"Efficiency,Hybrid,Electric,Vacation","SystemInHeating":"False","HotWaterVol":"High","Leak":"None","DryFire":"None","ElementFail":"None","TankSensorFail":"None","EcoError":"False","MasterDispFail":"None","CompSensorFail":"None","SysSensorFail":"None","SystemFail":"None","CondensePumpFail":"False","AirFilterStatus":"OK","UpperTemp":"131","LowerTemp":"132","FaultCodes":"0","UnConnectNumber":"3","AddrData":"05FD|00CD","SignalStrength":"-66"},"path":"/~branecky/postAll.php"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Setting device id","deviceId":"C47F5101CF2D"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Got Unit","unit":"°F"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"DeviceText"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"Password"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"ModuleApi"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key to sensor","key":"ModuleApi"}
{"level":10,"time":1744937359655,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Checking if unit is set"}
{"level":10,"time":1744937359655,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Publishing config","topic":"homeassistant/sensor/XXXXXXXX/moduleAPI/config","name":"moduleAPI"}
```

However, I still see the same SSL failures for some of the connections, and the bridge does not publish any sensor data on MQTT, even though it was present in the incoming JSON.

**Comment by Artem-B** [comment]
I can confirm that the IRIS module has trouble connecting. I've captured UART communication with the WiFi module on the chip and I see it failing:
```
[TCP SSL] Handshake Error
[TCP SSL] Advanced context, failed to connect
ERROR: Unknown Error
```

**Comment by Artem-B** [comment]
I've updated the firmware on the WiFi module to the most recent version and while it still fails to connect, the error message is a bit more informative:
```
[TCP SSL] No cert and/or key found.
```

The connection [setup commands ](https://www.inventeksys.com/iwin/wp-content/uploads/WiFi_AT_Command-_Set-Quick-Reference-1.pdf) indicate that verification is required (`P9=2`) and that connection will be closed on root CA verification failure (`PB=0`). So, in that sense the failure to connect is sort of expected as we just don't have a valid certificate signed by the known CA.

I wonder if it may be possible to sign bridge cert with self-signed CA certificate and add that CA certificate to the sensor. WiFi module appears to have `PG` command for that.

**Comment by starsoccer** [comment]
Id be interested to get more info about how you were able to update the wifi module as thats a bit beyond my skill. That PDF you shared is very interesting.

I am not sure why your device would be trying to validate the CA certificate. Most do not seem to which is the working assumption of this project and the original. If it is trying to validate it, I dont really see a way to make it work if you cant disable that. Short of getting a valid one, or some how getting the self signed certificate on the device like you mentioned.

**Comment by Artem-B** [comment]
Updating firmware is fairly straightforward and can be done via serial port or debug header. http://www.inventeksys.com/iwin/firmware-upgrades/
I can walk you through the process of updating it if you're interested, but that may not be relevant to the problem at hand.

Some observations:
- new firmware updates SSL connection to use TLS-1.2, so it supports wider range of hashes and ciphers. Not that it matters. Old version connected well enough.
- strict certificate checks are enabled only for connections to `devices.irissmarthome.com`. Connections to `energysmartheater.com` happen with disabled checks and do make it through to the bridge. That's what I see in the logs.
- what I do not see in the logs is the posting of the data that did make it to the bridge to MQTT. It appears to be an issue with processing the request on the bridge side.

The key difference is that right now the bridge never gets past "publishing config" for the `moduleAPI`, while previously it went directly into publishing states:

Now:
```
{"DeviceText":"XXXX","Password":"XXXX","ModuleApi":"1.5","ModFwVer":"3.1","MasterFwVer":"02.06","MasterModelId":"B2.00","DisplayFwVer":"00.00","WifiFwVer":"C2.4.0.3.AO7","UpdateRate":"300","Mode":"Electric","SetPoint":"132","Units":"F","LeakDetect":"NotDetected","MaxSetPoint":"132","Grid":"Enabled","AvailableModes":"Efficiency,Hybrid,Electric,Vacation","SystemInHeating":"False","HotWaterVol":"High","Leak":"None","DryFire":"None","ElementFail":"None","TankSensorFail":"None","EcoError":"False","MasterDispFail":"None","CompSensorFail":"None","SysSensorFail":"None","SystemFail":"None","CondensePumpFail":"False","AirFilterStatus":"OK","UpperTemp":"131","LowerTemp":"132","FaultCodes":"0","UnConnectNumber":"3","AddrData":"05FD|00CD","SignalStrength":"-66"},"path":"/~branecky/postAll.php"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Setting device id","deviceId":"XXXXX"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Got Unit","unit":"°F"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"DeviceText"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"Password"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"ModuleApi"}
{"level":10,"time":1744937359654,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key to sensor","key":"ModuleApi"}
{"level":10,"time":1744937359655,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Checking if unit is set"}
{"level":10,"time":1744937359655,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Publishing config","topic":"homeassistant/sensor/C47F5101CF2D/moduleAPI/config","name":"moduleAPI"}
... repeats previous line until the next connection arrives.
```

Working case:
```
{"DeviceText":"XXXXX","Password":"XXXXX","ModuleApi":"1.5","ModFwVer":"3.1","MasterFwVer":"02.06","MasterModelId":"B2.00","DisplayFwVer":"00.00","WifiFwVer":"C2.4.0.3.AO7","UpdateRate":"45","Mode":"Electric","SetPoint":"132","Units":"F","LeakDetect":"NotDetected","MaxSetPoint":"132","Grid":"Enabled","AvailableModes":"Efficiency,Hybrid,Electric,Vacation","SystemInHeating":"False","HotWaterVol":"High","Leak":"None","DryFire":"None","ElementFail":"None","TankSensorFail":"None","EcoError":"False","MasterDispFail":"None","CompSensorFail":"None","SysSensorFail":"None","SystemFail":"None","CondensePumpFail":"False","AirFilterStatus":"OK","UpperTemp":"127","LowerTemp":"118","FaultCodes":"0","UnConnectNumber":"56","AddrData":"05FD|00E2","SignalStrength":"-66"},"path":"/~branecky/postAll.php"}
{"level":10,"time":1744933350223,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Setting device id","deviceId":"XXXXXX"}
{"level":10,"time":1744933350223,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Got Unit","unit":"°F"}
{"level":10,"time":1744933350223,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"DeviceText"}
{"level":10,"time":1744933350223,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"Password"}
{"level":10,"time":1744933350223,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"ModuleApi"}
{"level":10,"time":1744933350223,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key to sensor","key":"ModuleApi"}
{"level":10,"time":1744933350223,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Publishing state","topic":"energysmartbridge/C47F5101CF2D/moduleAPI","name":"moduleAPI","value":"1.5"}
{"level":10,"time":1744933350224,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"ModFwVer"}
{"level":10,"time":1744933350224,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key to sensor","key":"ModFwVer"}
{"level":10,"time":1744933350224,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Publishing state","topic":"energysmartbridge/C47F5101CF2D/moduleFirmwareVersion","name":"moduleFirmwareVersion","value":"3.1"}
{"level":10,"time":1744933350224,"pid":21,"hostname":"03361182-energy-smart-bridge","message":"Converting key","key":"MasterFwVer"}
... a lot more...
```

**Comment by Artem-B** [comment]
Just in case, here's what IRIS is doing under the hood. Connections to `devices.irissmarthome.com` are the ones that have strict verification and are failing. Connections to `energysmartwaterheater.com` have verification disabled and work fine:
```
10:25:57.049 : D0=devices.irissmarthome.com
10:25:57.157 : CS
10:25:57.268 : P1=3
10:25:57.378 : P3=10.0.0.57
10:25:57.487 : P4=443
10:25:57.598 : P9=2
10:25:57.707 : PB=0
10:25:57.817 : CR
10:25:58.202 : P6=1
10:28:11.209 : D0=devices.irissmarthome.com
10:28:11.317 : CS
10:28:11.428 : P1=3
10:28:11.538 : P3=10.0.0.57
10:28:11.648 : P4=443
10:28:11.758 : P9=2
10:28:11.867 : PB=0
10:28:11.976 : CR
10:28:12.361 : P6=1
10:29:18.290 : D0=devices.irissmarthome.com
10:29:18.399 : CS
10:29:18.507 : P1=3
10:29:18.619 : P3=10.0.0.57
10:29:18.728 : P4=443
10:29:18.838 : P9=2
10:29:18.948 : PB=0
10:29:19.057 : CR
10:29:19.443 : P6=1
10:30:25.368 : D0=devices.irissmarthome.com
10:30:25.475 : CS
10:30:25.585 : P1=3
10:30:25.696 : P3=10.0.0.57
10:30:25.806 : P4=443
10:30:25.915 : P9=2
10:30:26.025 : PB=0
10:30:26.135 : CR
10:30:26.520 : P6=1
10:31:10.453 : D0=energysmartwaterheater.com
10:31:10.560 : CS
10:31:10.670 : P1=3
10:31:10.781 : P3=10.0.0.57
10:31:10.890 : P4=443
10:31:11.000 : P9=0
10:31:11.110 : PB=0
10:31:11.220 : CR
10:31:11.605 : P6=1
10:31:13.152 : S1=643
10:31:13.258 : S0
10:31:13.317 : POST /~branecky/postAll.php HTTP/1.1
10:31:13.320 : Host: energysmartwaterheater.com
10:31:13.324 : Content-Type: application/x-www-form-urlencoded
10:31:13.326 : Content-Length: 497

10:31:13.424 : DeviceText=XXXX&Password=XXXXXX&ModuleApi=1.5&ModFwVer=3.1&MasterFwVer=00.00&MasterModelId=00.00&DisplayFwVer=00.00&WifiFwVer=C6.2.1.11&UpdateRate=300&Mode=Unknown&SetPoint=0&Units=F&LeakDetect=NotDetected&MaxSetPoint=0&Grid=Dis6
10:31:13.533 : R0
10:31:15.733 : P6=0
10:31:15.843 : 
10:31:32.505 : D0=devices.irissmarthome.com
10:31:32.611 : CS
10:31:32.723 : P1=3
10:31:32.832 : P3=10.0.0.57
10:31:32.944 : P4=443
10:31:33.052 : P9=2
10:31:33.161 : PB=0
10:31:33.272 : CR
10:31:33.657 : P6=1

```

**Comment by Artem-B** [comment]
Based on the logs we appear to get stuck somewhere here:
https://github.com/starsoccer/energysmartbridge/blob/eaebf75a30296c410a485e9131e2989eb10230cc/energysmartbridge/src/waterheater.js#L64-L71
which heads here:
https://github.com/starsoccer/energysmartbridge/blob/eaebf75a30296c410a485e9131e2989eb10230cc/energysmartbridge/src/baseSensor.js#L23-L25

and we get stuck in `publishConfig()` never making it to the `publishState()`:

https://github.com/starsoccer/energysmartbridge/blob/eaebf75a30296c410a485e9131e2989eb10230cc/energysmartbridge/src/sensor.js#L33-L44


So, something to do with MQTT? Not sure how to debug it further. For what it's worth, mosquitto instance in HA that the bridge is connected to is up and running and I see it delivering messages. I also see the old sensor states (from before I've updated the firmware) posted by the bridge when it was working.

However, I do *not* see the topic `homeassistant/sensor/C47F5101CF2D/moduleAPI/config` it's getting stuck on.

**Comment by Artem-B** [comment]
Ugh. That was indeed MQTT and it was a self inflicting problem. MQTT host was set to `homeassistant.local` and for whatever reason resolving that name was getting completely stuck in the container. Changing configuration to point to the actual resolvable host name resolvable fixed my issue. Now the bridge posts sensor data w/o issues.

I guess this silent failure is due to the async nature of the bridge. If MQTT connection gets stuck, we do not notice it until we try to actually publish something. Perhaps it might be a good idea to connect to MQTT synchronously, with a timeout on start-up and diagnose connectivity issues early on.

**Comment by starsoccer** [comment]
> Ugh. That was indeed MQTT and it was a self inflicted problem. MQTT host was set to `homeassistant.local` and for whatever reason resolving that name was getting completely stuck in the container. Changing configuration to point to the actual resolvable host name fixed my issue. Now the bridge posts sensor data w/o issues.
> 
> I guess this silent failure is due to the async nature of the bridge. If MQTT connection gets stuck, we do not notice it until we try to actually publish something. Perhaps it might be a good idea to connect to MQTT synchronously, with a timeout on start-up and diagnose connectivity issues early on.

Well I am glad you got it to work finally. I just published a new version 1.0.8 which adds mqtt error logging so if it cant connect it will now atleast log an error.

Going to close this issue if its now resolved but if you have any other problems, just let me know.
